default: &default
  adapter: postgresql
  username: postgres
  password: qwerty
  host: localhost
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: test_ror_development

test:
  <<: *default
  database: test_ror_test

production:
  <<: *default
  database: test_ror_production
